/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package distributedsupershop;

import java.awt.Image;
import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class AdminPortal2 extends javax.swing.JFrame {

    DataBaseConnection2 db = new DataBaseConnection2();
    static int status;
    int choice1, choice2;
    JTextField products [];
    JLabel labels[]; 
    String dateStart, dateEnd;
    public AdminPortal2(int status) {
        AdminPortal2.status = status;
        try {
            initComponents();
            setContentPane(new javax.swing.JLabel(new ImageIcon(
                    "shade8.png")));
            jLabel6.setIcon(new ImageIcon(ImageIO.read(new java.io.File("Cart.png")
            ).getScaledInstance(jLabel6.getWidth(), jLabel6.getHeight(),
                    Image.SCALE_SMOOTH)));
            jLabel9.setIcon(new ImageIcon(ImageIO.read(new java.io.File("back5.png")
            ).getScaledInstance(jLabel9.getWidth(), jLabel9.getHeight(),
                    Image.SCALE_SMOOTH)));
             jLabel11.setIcon(new ImageIcon(ImageIO.read(new java.io.File("exit.png")
            ).getScaledInstance(jLabel11.getWidth(), jLabel11.getHeight(),
                    Image.SCALE_SMOOTH)));
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        jComboBox1.removeAllItems();
        ArrayList list = db.getBranchList();
        list.add("All branches");
        for (int i = 0; i < list.size(); i++){
            jComboBox1.addItem(list.get(i));
        }
        add(jComboBox1); add(jLabel1); add(jLabel10); add(jLabel6); add(jLabel2); add(jTextField1);
        add(jButton1);  add(jLabel12); add(jLabel13);add(jLabel11);add(jLabel9); add(jButton1);
        add(jLabel4); add(jScrollPane1);
         
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel10.setFont(new java.awt.Font("Calibri Light", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 153));
        jLabel10.setText("Distributed SuperShop System");

        jLabel1.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setText("Select Branch:");

        jComboBox1.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 102, 153));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel2.setText("Insert Product ID:");

        jTextField1.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 102, 153));

        jLabel12.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 153));
        jLabel12.setText("Exit");

        jLabel13.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 153));
        jLabel13.setText("Back");

        jLabel9.setText("jLabel7");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel11.setText("jLabel7");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 153));
        jLabel4.setText("Admin Portal: Customer");

        jScrollPane1.setOpaque(false);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "Customer Name", "Address", "Membership Start", "Membership End", "Points"
            }
        ));
        jTable1.setFillsViewportHeight(true);
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(255, 204, 255));
        jButton1.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 153));
        jButton1.setText("Go");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(55, 55, 55)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(416, 416, 416)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(150, 150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(31, 31, 31))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
            this.setVisible(false);this.dispose();
            new AdminPortal(status).setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        this.setVisible(false); this.dispose(); System.exit(0);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(status == 0)
        {String selection= jComboBox1.getSelectedItem().toString();
            //int id=0;
            //if(!jTextField1.getText().equals("")){id = Integer.parseInt(jTextField1.getText());}
            
        if(!selection.equals("All branches"))
            {String sql="select Branch_ipaddress,Branch_port from Branches where Branch_name=?";
                try{
                    DataBaseConnection db = new DataBaseConnection();
                    db.pstmt= db.con.prepareStatement(sql);
                    db.pstmt.setString(1,selection);
                    db.rs=db.pstmt.executeQuery();
                    if(db.rs.next()){
                        String Branch_ipaddress = db.rs.getString("Branch_ipaddress");
                        int Branch_port = db.rs.getInt("Branch_port");
                        Client client= new Client(Branch_ipaddress, Branch_port);
                        client.printStrm.println(8);
                        int cont = client.scanner.nextInt();
                        while(cont==1){
                            int customer_id= client.scanner.nextInt();
                            int membership_points= client.scanner.nextInt();
                            int len = client.scanner.nextInt();
                            char [] X = new char [len];
                            for (int i=0; i<len; i++){
                                int x=client.scanner.nextInt();
                                X[i] = (char) x;
                            }
                            String customer_name = new String (X);
                            len = client.scanner.nextInt();
                            char [] Y = new char [len];
                            for (int i=0; i<len; i++){
                                int x=client.scanner.nextInt();
                                Y[i] = (char) x;
                            }
                            String customer_address = new String (Y);
                            len = client.scanner.nextInt();
                            char [] Z = new char [len];
                            for (int i=0; i<len; i++){
                                int x=client.scanner.nextInt();
                                Z[i] = (char) x;
                            }
                            String membership_start = new String (Z);
                            len = client.scanner.nextInt();
                            char [] W = new char [len];
                            for (int i=0; i<len; i++){
                                int x=client.scanner.nextInt();
                                W[i] = (char) x;
                            }
                            String membership_end = new String (W);
                            ((DefaultTableModel)jTable1.getModel()).addRow(new Object[]{customer_id,customer_name,customer_address,membership_start,membership_end,membership_points});
                            ((AbstractTableModel)jTable1.getModel()).fireTableDataChanged();
                            cont = client.scanner.nextInt();
                        }
                    }}
                    catch(Exception ex){ex.printStackTrace();}}
                else{
                    try {
                        DataBaseConnection db = new DataBaseConnection();
                        db.rs=db.stmt.executeQuery("select * from branches");
                        while(db.rs.next()){
                            String Branch_ipaddress = db.rs.getString("Branch_ipaddress");
                            int Branch_port = db.rs.getInt("Branch_port");
                            Client client= new Client(Branch_ipaddress, Branch_port);
                            client.printStrm.println(8);
                            int cont = client.scanner.nextInt();
                            while(cont==1){
                                int customer_id= client.scanner.nextInt();
                                int membership_points= client.scanner.nextInt();
                                int len = client.scanner.nextInt();
                                char [] X = new char [len];
                                for (int i=0; i<len; i++){
                                    int x=client.scanner.nextInt();
                                    X[i] = (char) x;
                                }
                                String customer_name = new String (X);
                                len = client.scanner.nextInt();
                                char [] Y = new char [len];
                                for (int i=0; i<len; i++){
                                    int x=client.scanner.nextInt();
                                    Y[i] = (char) x;
                                }
                                String customer_address = new String (Y);
                                len = client.scanner.nextInt();
                                char [] Z = new char [len];
                                for (int i=0; i<len; i++){
                                    int x=client.scanner.nextInt();
                                    Z[i] = (char) x;
                                }
                                String membership_start = new String (Z);
                                len = client.scanner.nextInt();
                                char [] W = new char [len];
                                for (int i=0; i<len; i++){
                                    int x=client.scanner.nextInt();
                                    W[i] = (char) x;
                                }
                                String membership_end = new String (W);
                                ((DefaultTableModel)jTable1.getModel()).addRow(new Object[]{customer_id,customer_name,customer_address,membership_start,membership_end,membership_points});
                                ((AbstractTableModel)jTable1.getModel()).fireTableDataChanged();
                                cont = client.scanner.nextInt();
                            }
                        }
                    } catch (SQLException ex) {
                        ex.printStackTrace();
                    }
                }
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPortal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPortal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPortal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPortal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPortal2(status).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
