/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package distributedsupershop;

import java.awt.Image;
import java.io.IOException;
import java.sql.Timestamp;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodela
 */
public class Login extends javax.swing.JFrame {

    /**
     *
     * Creates new form Login
     */
    public Login() {

        initComponents();
         setContentPane(new javax.swing.JLabel(new ImageIcon(
                    "shade3.png"))); 
         try{
             jLabel6.setIcon(new ImageIcon(ImageIO.read(new java.io.File("Cart.png")
            ).getScaledInstance(jLabel6.getWidth(), jLabel6.getHeight(),
                    Image.SCALE_SMOOTH)));
             
             jLabel1.setIcon(new ImageIcon(ImageIO.read(new java.io.File("backyellow.png")
            ).getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(),
                    Image.SCALE_SMOOTH)));
             
         }
          catch (IOException ex) {
            System.out.println(ex);
        }
          add(jTextFieldUserID); add(jPasswordFieldlog);add(jLabelUserID);add(jLabelPass);add(jLabel5);
          add(jLabel6);add(jLabel10);add(jButtonClearLog);add(jButtonLogAdmin);
        add(jButtonLogEmp);
    add(jLabel1);add(jLabel2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelUserID = new javax.swing.JLabel();
        jTextFieldUserID = new javax.swing.JTextField();
        jLabelPass = new javax.swing.JLabel();
        jButtonLogAdmin = new javax.swing.JButton();
        jButtonLogEmp = new javax.swing.JButton();
        jButtonClearLog = new javax.swing.JButton();
        jPasswordFieldlog = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1080, 1021));

        jLabelUserID.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabelUserID.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUserID.setText("  User Name");

        jLabelPass.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabelPass.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPass.setText("Password");

        jButtonLogAdmin.setBackground(new java.awt.Color(255, 204, 204));
        jButtonLogAdmin.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jButtonLogAdmin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogAdmin.setText("Login as Admin");
        jButtonLogAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogAdminActionPerformed(evt);
            }
        });

        jButtonLogEmp.setBackground(new java.awt.Color(255, 204, 204));
        jButtonLogEmp.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jButtonLogEmp.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogEmp.setText("Login as Employee");
        jButtonLogEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogEmpActionPerformed(evt);
            }
        });

        jButtonClearLog.setBackground(new java.awt.Color(255, 204, 204));
        jButtonClearLog.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jButtonClearLog.setForeground(new java.awt.Color(255, 255, 255));
        jButtonClearLog.setText("Clear");
        jButtonClearLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearLogActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Login Form");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel10.setFont(new java.awt.Font("Calibri Light", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Distributed SuperShop System");

        jLabel1.setText("jLabel1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146))
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(0, 334, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPass, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonClearLog, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2))))
                    .addComponent(jLabelUserID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonLogAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLogEmp))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldUserID)
                    .addComponent(jPasswordFieldlog, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(271, 271, 271))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel10)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordFieldlog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClearLog)
                    .addComponent(jButtonLogEmp)
                    .addComponent(jButtonLogAdmin))
                .addContainerGap(326, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogAdminActionPerformed
        this.setVisible(false);
            try {
                String sql = "select * from AdminLogin where User_name='" + jTextFieldUserID.getText() + "' and Password='" + jPasswordFieldlog.getText() + "'";
                String sql1 = "insert into Adminlog_history (Adminlog_time,log_Admin_name) values (?,?)";
                DataBaseConnection db = new DataBaseConnection();
                db.pstmt = db.con.prepareStatement(sql);
                db.rs = db.pstmt.executeQuery();
                if (db.rs.next()) {
                    JOptionPane.showMessageDialog(null, "Login is successful.");
                    int id = db.rs.getInt("admin_id");
                    db.pstmt = db.con.prepareStatement(sql1);
                    db.pstmt.setTimestamp(1, new Timestamp(System.currentTimeMillis()));
                    db.pstmt.setString(2, jTextFieldUserID.getText());
                    db.rs = db.pstmt.executeQuery();
                    if(id == 10061) new Menu(0).setVisible(true);
                    else new Menu(1).setVisible(true);
                } 
                else {
                    JOptionPane.showMessageDialog(null, "Login Failed.");
                    this.setVisible(false); this.dispose(); Login log=new Login();
                    log.setVisible(true);
                }
            } 
            catch (Exception e) {
                e.printStackTrace(); JOptionPane.showMessageDialog(null, "Login Failed."); 
                this.setVisible(false); this.dispose(); Login log=new Login();
                log.setVisible(true);
            }
    }//GEN-LAST:event_jButtonLogAdminActionPerformed

    private void jButtonLogEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogEmpActionPerformed
        this.setVisible(false);
        try {
                String sql = "select E_User_name, E_Password from EmpLogin where E_User_name='" + jTextFieldUserID.getText() + "' and E_Password='" + jPasswordFieldlog.getText() + "'";
                String sql1 = "insert into Emplog_history (Emplog_time,log_Emp_name) values (?,?)";
                DataBaseConnection db = new DataBaseConnection();
                db.pstmt = db.con.prepareStatement(sql);
                db.rs = db.pstmt.executeQuery();
                    
                if (db.rs.next()) {
                    JOptionPane.showMessageDialog(null, "Login is successful.");
                    db.pstmt = db.con.prepareStatement(sql1);
                    db.pstmt.setTimestamp(1, new Timestamp(System.currentTimeMillis()));
                    db.pstmt.setString(2, jTextFieldUserID.getText());
                    db.rs = db.pstmt.executeQuery();
                    new Menu(2).setVisible(true);
                } 
                else {
                    JOptionPane.showMessageDialog(null, "Login Failed.");
                    this.setVisible(false); this.dispose(); Login log=new Login();
                    log.setVisible(true);
                }
            } 
        catch (Exception e) {
                e.printStackTrace();JOptionPane.showMessageDialog(null, "Login Failed."); 
                this.setVisible(false); this.dispose(); Login log=new Login();
                log.setVisible(true);
            }
    }//GEN-LAST:event_jButtonLogEmpActionPerformed

    private void jButtonClearLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearLogActionPerformed
        jTextFieldUserID.setText("");
        jPasswordFieldlog.setText("");
    }//GEN-LAST:event_jButtonClearLogActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.setVisible(false);
        new Welcome().setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClearLog;
    private javax.swing.JButton jButtonLogAdmin;
    private javax.swing.JButton jButtonLogEmp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelPass;
    private javax.swing.JLabel jLabelUserID;
    private javax.swing.JPasswordField jPasswordFieldlog;
    private javax.swing.JTextField jTextFieldUserID;
    // End of variables declaration//GEN-END:variables
}
